import "@/app/globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Suspense } from "react";
import IndexLoader from "@/components/ui/loader/index-loader";
import { LoaderSpin } from "@/components/ui/loader";
import { Toaster } from "sonner";
import { getUserEmail } from "@/lib/session/session";
import serverApiRequest from "@/utils/api/server-api-request";
import GET_USER_ACCOUNT_BY_EMAIL from "@/utils/endpoints/external/user/get-by-email";
import { AuthProvider, AuthUser } from "@/utils/context/AuthContext";
import { GlobalLoadingProvider } from "@/components/ui/loader/global-loading-provider";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "TouchWood",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const userEmail = await getUserEmail();

	let userAccountDetails = null;
	if (userEmail) {
		const { data } = await serverApiRequest({
			connection: GET_USER_ACCOUNT_BY_EMAIL(userEmail),
		});
		userAccountDetails = data;
	}

	const authUser: AuthUser | null = userAccountDetails
		? {
				email: userAccountDetails.email,
				phoneVerified: userAccountDetails.phoneVerified,
				emailVerified: userAccountDetails.emailVerified,
				username: userAccountDetails.username,
				firstName: userAccountDetails.firstName,
				lastName: userAccountDetails.lastName,
				userId: userAccountDetails.id,
			}
		: null;

	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} flex min-h-screen flex-col antialiased`}
			>
				<Toaster
					richColors
					position="top-center"
					closeButton
					swipeDirections={["right"]}
				/>
				<AuthProvider initialUser={authUser}>
					<Suspense
						fallback={
							<IndexLoader>
								<LoaderSpin
									width={100}
									height={100}
									color="#078BA0"
									className=""
								/>
							</IndexLoader>
						}
					>
						<GlobalLoadingProvider>{children}</GlobalLoadingProvider>
					</Suspense>
				</AuthProvider>
			</body>
		</html>
	);
}
