import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Toaster } from 'react-hot-toast';
import GuestNavBar from '@/components/ui/nav-bar/guest-nav-bar';
import { Suspense } from 'react';
import IndexLoader from '@/components/ui/loader/index-loader';
import { LoaderSpin } from '@/components/ui/loader';
import Sidebar from '@/components/ui/sidebar/sidebar';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'TouchWood',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex min-h-screen flex-col antialiased`}
      >
        <GuestNavBar className="fixed top-0 z-50" />
        <Toaster position="top-center" reverseOrder={false} />
        <Suspense
          fallback={
            <IndexLoader>
              <LoaderSpin
                width={50}
                height={50}
                color="#078BA0"
                className="h-6 w-6 lg:h-8 lg:w-8"
              />
            </IndexLoader>
          }
        >
          <div className="relative flex h-screen">
            <Sidebar />
            <div className="relative z-0 w-full">{children}</div>
          </div>
        </Suspense>
      </body>
    </html>
  );
}
